name: Update Followers

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install requests

      - run: python tracker.py

      - run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add data.json
          git commit -m "update followers" || echo "no change"
          git push
