name: Update TikTok Followers

on:
  schedule:
    - cron: "*/1 * * * *"  # hvert minut
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python tracker.py

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "auto update" || echo "no changes"
          git push
